
export const readingText = `דני הוא תלמיד בן 14 שאוהב מאוד בעלי חיים. אחת לשבוע הוא מבקר בגן החיות העירוני, שם הוא מתנדב בטיפול בבעלי החיים. החיה האהובה עליו היא הפיל – הוא מתרשם מהגודל שלו, מהאינטליגנציה שלו ומההתנהגות הרגועה שלו. ביום ההולדת שלו, המטפל הראשי אפשר לדני להאכיל את הפיל – ודני הרגיש שזו הייתה חוויה בלתי נשכחת.`;

export const translationMap: { [hebrewWord: string]: string } = {
  "דני": "Dani",
  "תלמיד": "student",
  "בן": "age",
  "שנה": "year",
  "אוהב": "loves",
  "מאוד": "very",
  "בעלי": "animals (when in 'בעלי חיים')",
  "חיים": "life / animals",
  "אחת": "once",
  "לשבוע": "per week",
  "מבקר": "visits",
  "גן": "zoo",
  "החיות": "the animals",
  "העירוני": "municipal / city",
  "מתנדב": "volunteers",
  "בטיפול": "in caring",
  "החיה": "the animal",
  "האהובה": "favorite",
  "עליו": "of his",
  "הפיל": "the elephant",
  "מתרשם": "is impressed",
  "הגודל": "the size",
  "האינטליגנציה": "the intelligence",
  "ההתנהגות": "the behavior",
  "הרגועה": "calm",
  "ביום": "on (the)",
  "ההולדת": "birthday",
  "שלו": "his",
  "המטפל": "the caretaker",
  "הראשי": "main",
  "אפשר": "allowed",
  "להאכיל": "to feed",
  "חוויה": "an experience",
  "בלתי": "un- (as in unforgettable)",
  "נשכחת": "forgotten"
};

