
export const readingText = `איתי וחברתו מאיה הגיעו למסעדה חדשה בעיר. המלצר הציג בפניהם תפריט מגוון: מרק ירקות, חומוס, שניצל וצ'יפס, ושלל קינוחים. מאיה התלבטה בין סלט טונה לפיצה, ובסוף בחרה במרק ובפיצה משפחתית. איתי התעקש להזמין חומוס עם הרבה טחינה ולימונדה קרה. אחרי הארוחה, המלצר הציע להם כנאפה לקינוח, והם חלקו אותו בשמחה. בסוף, מאיה נזכרה שהיא שכחה לאכול מהפיצה, כי כל כך נהנתה מהמרק!`;

export const translationMap: { [hebrewWord: string]: string } = {
  "איתי": "Itay",
  "חברתו": "his girlfriend",
  "מאיה": "Maya",
  "מסעדה": "restaurant",
  "חדשה": "new",
  "בעיר": "in the city",
  "המלצר": "the waiter",
  "הציג": "presented",
  "בפניהם": "to them",
  "תפריט": "menu",
  "מגוון": "varied",
  "מרק": "soup",
  "ירקות": "vegetables",
  "חומוס": "hummus",
  "שניצל": "schnitzel",
  "וצ'יפס": "and chips",
  "שלל": "a variety of",
  "קינוחים": "desserts",
  "מאיה": "Maya",
  "התלבטה": "hesitated",
  "בין": "between",
  "סלט": "salad",
  "טונה": "tuna",
  "לפיצה": "and pizza",
  "לבסוף": "finally",
  "בחרה": "chose",
  "במרק": "the soup",
  "בפיצה": "the pizza",
  "משפחתית": "family-size",
  "איתי": "Itay",
  "התעקש": "insisted",
  "להזמין": "to order",
  "עם": "with",
  "הרבה": "lots of",
  "טחינה": "tahini",
  "ולימונדה": "and lemonade",
  "קרה": "cold",
  "אחרי": "after",
  "הארוחה": "the meal",
  "הציע": "offered",
  "כנאפה": "knafeh (dessert)",
  "לקינוח": "for dessert",
  "חלקו": "shared",
  "בשמחה": "happily",
  "בסוף": "at the end",
  "נזכרה": "remembered",
  "שהיא": "that she",
  "שכחה": "forgot",
  "לאכול": "to eat",
  "מהפיצה": "from the pizza",
  "נהנתה": "enjoyed",
  "כל כך": "so much",
  "מהמרק": "the soup"
};
