export interface OddOneOutQuestion {
  id: number;
  words: { word: string; withNikud: string }[];
  oddIndex: number;
  explanation: string;
  explanationEn: string;
  category: string;
}

export const easyQuestions: OddOneOutQuestion[] = [
  {
    id: 1,
    words: [
      { word: "תפוח", withNikud: "תַּפּוּחַ" },
      { word: "בננה", withNikud: "בָּנָנָה" },
      { word: "תפוז", withNikud: "תַּפּוּז" },
      { word: "כיסא", withNikud: "כִּיסֵא" },
    ],
    oddIndex: 3,
    explanation: "כיסא הוא רהיט, השאר פירות",
    explanationEn: "Chair is furniture, the rest are fruits",
    category: "פירות",
  },
  {
    id: 2,
    words: [
      { word: "כלב", withNikud: "כֶּלֶב" },
      { word: "חתול", withNikud: "חָתוּל" },
      { word: "ספר", withNikud: "סֵפֶר" },
      { word: "ציפור", withNikud: "צִפּוֹר" },
    ],
    oddIndex: 2,
    explanation: "ספר הוא חפץ, השאר חיות",
    explanationEn: "Book is an object, the rest are animals",
    category: "חיות",
  },
  {
    id: 3,
    words: [
      { word: "אדום", withNikud: "אָדֹם" },
      { word: "ירוק", withNikud: "יָרֹק" },
      { word: "כחול", withNikud: "כָּחֹל" },
      { word: "גדול", withNikud: "גָּדוֹל" },
    ],
    oddIndex: 3,
    explanation: "גדול הוא גודל, השאר צבעים",
    explanationEn: "Big is a size, the rest are colors",
    category: "צבעים",
  },
  {
    id: 4,
    words: [
      { word: "ראשון", withNikud: "רִאשׁוֹן" },
      { word: "שני", withNikud: "שֵׁנִי" },
      { word: "שלישי", withNikud: "שְׁלִישִׁי" },
      { word: "שולחן", withNikud: "שֻׁלְחָן" },
    ],
    oddIndex: 3,
    explanation: "שולחן הוא רהיט, השאר ימים בשבוע",
    explanationEn: "Table is furniture, the rest are days of the week",
    category: "ימים",
  },
  {
    id: 5,
    words: [
      { word: "אמא", withNikud: "אִמָּא" },
      { word: "אבא", withNikud: "אַבָּא" },
      { word: "אח", withNikud: "אָח" },
      { word: "מכונית", withNikud: "מְכוֹנִית" },
    ],
    oddIndex: 3,
    explanation: "מכונית היא כלי רכב, השאר בני משפחה",
    explanationEn: "Car is a vehicle, the rest are family members",
    category: "משפחה",
  },
  {
    id: 6,
    words: [
      { word: "אחד", withNikud: "אֶחָד" },
      { word: "שתיים", withNikud: "שְׁתַּיִם" },
      { word: "שלוש", withNikud: "שָׁלוֹשׁ" },
      { word: "בית", withNikud: "בַּיִת" },
    ],
    oddIndex: 3,
    explanation: "בית הוא מבנה, השאר מספרים",
    explanationEn: "House is a building, the rest are numbers",
    category: "מספרים",
  },
  {
    id: 7,
    words: [
      { word: "לחם", withNikud: "לֶחֶם" },
      { word: "חלב", withNikud: "חָלָב" },
      { word: "גבינה", withNikud: "גְּבִינָה" },
      { word: "עיפרון", withNikud: "עִפָּרוֹן" },
    ],
    oddIndex: 3,
    explanation: "עיפרון הוא כלי כתיבה, השאר מאכלים",
    explanationEn: "Pencil is a writing tool, the rest are foods",
    category: "אוכל",
  },
  {
    id: 8,
    words: [
      { word: "יד", withNikud: "יָד" },
      { word: "רגל", withNikud: "רֶגֶל" },
      { word: "ראש", withNikud: "רֹאשׁ" },
      { word: "דלת", withNikud: "דֶּלֶת" },
    ],
    oddIndex: 3,
    explanation: "דלת היא חפץ, השאר איברי גוף",
    explanationEn: "Door is an object, the rest are body parts",
    category: "גוף",
  },
  {
    id: 9,
    words: [
      { word: "שמש", withNikud: "שֶׁמֶשׁ" },
      { word: "ירח", withNikud: "יָרֵחַ" },
      { word: "כוכב", withNikud: "כּוֹכָב" },
      { word: "מיטה", withNikud: "מִיטָה" },
    ],
    oddIndex: 3,
    explanation: "מיטה היא רהיט, השאר גרמי שמיים",
    explanationEn: "Bed is furniture, the rest are celestial bodies",
    category: "שמיים",
  },
  {
    id: 10,
    words: [
      { word: "מים", withNikud: "מַיִם" },
      { word: "מיץ", withNikud: "מִיץ" },
      { word: "קפה", withNikud: "קָפֶה" },
      { word: "נעל", withNikud: "נַעַל" },
    ],
    oddIndex: 3,
    explanation: "נעל היא ביגוד, השאר משקאות",
    explanationEn: "Shoe is clothing, the rest are drinks",
    category: "שתייה",
  },
];

export const mediumQuestions: OddOneOutQuestion[] = [
  {
    id: 1,
    words: [
      { word: "רופא", withNikud: "רוֹפֵא" },
      { word: "מורה", withNikud: "מוֹרֶה" },
      { word: "שופט", withNikud: "שׁוֹפֵט" },
      { word: "מהיר", withNikud: "מָהִיר" },
    ],
    oddIndex: 3,
    explanation: "מהיר היא תואר, השאר מקצועות",
    explanationEn: "Fast is an adjective, the rest are professions",
    category: "מקצועות",
  },
  {
    id: 2,
    words: [
      { word: "הלך", withNikud: "הָלַךְ" },
      { word: "רץ", withNikud: "רָץ" },
      { word: "קפץ", withNikud: "קָפַץ" },
      { word: "יפה", withNikud: "יָפֶה" },
    ],
    oddIndex: 3,
    explanation: "יפה היא תואר, השאר פעלים של תנועה",
    explanationEn: "Beautiful is an adjective, the rest are movement verbs",
    category: "פעלים",
  },
  {
    id: 3,
    words: [
      { word: "תל אביב", withNikud: "תֵּל אָבִיב" },
      { word: "ירושלים", withNikud: "יְרוּשָׁלַיִם" },
      { word: "חיפה", withNikud: "חֵיפָה" },
      { word: "ישראל", withNikud: "יִשְׂרָאֵל" },
    ],
    oddIndex: 3,
    explanation: "ישראל היא מדינה, השאר ערים",
    explanationEn: "Israel is a country, the rest are cities",
    category: "גאוגרפיה",
  },
  {
    id: 4,
    words: [
      { word: "שמח", withNikud: "שָׂמֵחַ" },
      { word: "עצוב", withNikud: "עָצוּב" },
      { word: "כועס", withNikud: "כּוֹעֵס" },
      { word: "לרוץ", withNikud: "לָרוּץ" },
    ],
    oddIndex: 3,
    explanation: "לרוץ הוא פועל, השאר רגשות",
    explanationEn: "To run is a verb, the rest are emotions",
    category: "רגשות",
  },
  {
    id: 5,
    words: [
      { word: "ינואר", withNikud: "יָנוּאָר" },
      { word: "פברואר", withNikud: "פֶבְּרוּאָר" },
      { word: "מרץ", withNikud: "מֶרְץ" },
      { word: "שבת", withNikud: "שַׁבָּת" },
    ],
    oddIndex: 3,
    explanation: "שבת הוא יום בשבוע, השאר חודשים",
    explanationEn: "Saturday is a day, the rest are months",
    category: "זמן",
  },
  {
    id: 6,
    words: [
      { word: "כתב", withNikud: "כָּתַב" },
      { word: "קרא", withNikud: "קָרָא" },
      { word: "למד", withNikud: "לָמַד" },
      { word: "קטן", withNikud: "קָטָן" },
    ],
    oddIndex: 3,
    explanation: "קטן הוא תואר, השאר פעלים",
    explanationEn: "Small is an adjective, the rest are verbs",
    category: "פעלים",
  },
  {
    id: 7,
    words: [
      { word: "מטבח", withNikud: "מִטְבָּח" },
      { word: "סלון", withNikud: "סָלוֹן" },
      { word: "חדר שינה", withNikud: "חֲדַר שֵׁינָה" },
      { word: "רחוב", withNikud: "רְחוֹב" },
    ],
    oddIndex: 3,
    explanation: "רחוב הוא מקום חיצוני, השאר חדרים בבית",
    explanationEn: "Street is outside, the rest are rooms in a house",
    category: "בית",
  },
  {
    id: 8,
    words: [
      { word: "גיטרה", withNikud: "גִּיטָרָה" },
      { word: "פסנתר", withNikud: "פְּסַנְתֵּר" },
      { word: "כינור", withNikud: "כִּינּוֹר" },
      { word: "ציור", withNikud: "צִיּוּר" },
    ],
    oddIndex: 3,
    explanation: "ציור הוא אמנות חזותית, השאר כלי נגינה",
    explanationEn: "Painting is visual art, the rest are musical instruments",
    category: "מוזיקה",
  },
  {
    id: 9,
    words: [
      { word: "עורך דין", withNikud: "עוֹרֵךְ דִּין" },
      { word: "שוטר", withNikud: "שׁוֹטֵר" },
      { word: "שופט", withNikud: "שׁוֹפֵט" },
      { word: "טבח", withNikud: "טַבָּח" },
    ],
    oddIndex: 3,
    explanation: "טבח עובד במטבח, השאר קשורים למשפט",
    explanationEn: "Chef works in kitchen, the rest are related to law",
    category: "מקצועות",
  },
  {
    id: 10,
    words: [
      { word: "אתמול", withNikud: "אֶתְמוֹל" },
      { word: "היום", withNikud: "הַיּוֹם" },
      { word: "מחר", withNikud: "מָחָר" },
      { word: "פה", withNikud: "פֹּה" },
    ],
    oddIndex: 3,
    explanation: "פה הוא מקום, השאר זמנים",
    explanationEn: "Here is a place, the rest are times",
    category: "זמן",
  },
  {
    id: 11,
    words: [
      { word: "כביש", withNikud: "כְּבִישׁ" },
      { word: "מדרכה", withNikud: "מִדְרָכָה" },
      { word: "גשר", withNikud: "גֶּשֶׁר" },
      { word: "מחברת", withNikud: "מַחְבֶּרֶת" },
    ],
    oddIndex: 3,
    explanation: "מחברת היא כלי כתיבה, השאר קשורים לדרכים",
    explanationEn: "Notebook is for writing, the rest are related to roads",
    category: "תחבורה",
  },
  {
    id: 12,
    words: [
      { word: "חורף", withNikud: "חֹרֶף" },
      { word: "קיץ", withNikud: "קַיִץ" },
      { word: "אביב", withNikud: "אָבִיב" },
      { word: "בוקר", withNikud: "בֹּקֶר" },
    ],
    oddIndex: 3,
    explanation: "בוקר הוא זמן ביום, השאר עונות",
    explanationEn: "Morning is time of day, the rest are seasons",
    category: "עונות",
  },
];

export const hardQuestions: OddOneOutQuestion[] = [
  {
    id: 1,
    words: [
      { word: "גבוה", withNikud: "גָּבוֹהַּ" },
      { word: "נמוך", withNikud: "נָמוּךְ" },
      { word: "ארוך", withNikud: "אָרֹךְ" },
      { word: "גובה", withNikud: "גֹּבַהּ" },
    ],
    oddIndex: 3,
    explanation: "גובה הוא שם עצם, השאר תארים",
    explanationEn: "Height is a noun, the rest are adjectives",
    category: "דקדוק",
  },
  {
    id: 2,
    words: [
      { word: "לרוץ", withNikud: "לָרוּץ" },
      { word: "ללכת", withNikud: "לָלֶכֶת" },
      { word: "לשבת", withNikud: "לָשֶׁבֶת" },
      { word: "ריצה", withNikud: "רִיצָה" },
    ],
    oddIndex: 3,
    explanation: "ריצה הוא שם עצם, השאר פעלים במקור",
    explanationEn: "Running is a noun, the rest are infinitive verbs",
    category: "דקדוק",
  },
  {
    id: 3,
    words: [
      { word: "שולחן", withNikud: "שֻׁלְחָן" },
      { word: "כיסא", withNikud: "כִּיסֵא" },
      { word: "ארון", withNikud: "אָרוֹן" },
      { word: "מנורה", withNikud: "מְנוֹרָה" },
    ],
    oddIndex: 3,
    explanation: "מנורה היא נקבה, השאר זכר",
    explanationEn: "Lamp is feminine, the rest are masculine",
    category: "מין דקדוקי",
  },
  {
    id: 4,
    words: [
      { word: "ילד", withNikud: "יֶלֶד" },
      { word: "ילדה", withNikud: "יַלְדָּה" },
      { word: "ילדים", withNikud: "יְלָדִים" },
      { word: "ילדות", withNikud: "יַלְדוּת" },
    ],
    oddIndex: 3,
    explanation: "ילדות היא מושג מופשט, השאר אנשים",
    explanationEn: "Childhood is abstract, the rest are people",
    category: "דקדוק",
  },
  {
    id: 5,
    words: [
      { word: "חם", withNikud: "חַם" },
      { word: "קר", withNikud: "קַר" },
      { word: "חמים", withNikud: "חַמִּים" },
      { word: "קור", withNikud: "קֹר" },
    ],
    oddIndex: 3,
    explanation: "קור הוא שם עצם, השאר תארים",
    explanationEn: "Cold (noun) is a noun, the rest are adjectives",
    category: "דקדוק",
  },
  {
    id: 6,
    words: [
      { word: "אכל", withNikud: "אָכַל" },
      { word: "שתה", withNikud: "שָׁתָה" },
      { word: "ישן", withNikud: "יָשַׁן" },
      { word: "אוכל", withNikud: "אֹכֶל" },
    ],
    oddIndex: 3,
    explanation: "אוכל הוא שם עצם (מזון), השאר פעלים בעבר",
    explanationEn: "Food is a noun, the rest are past tense verbs",
    category: "דקדוק",
  },
  {
    id: 7,
    words: [
      { word: "עיר", withNikud: "עִיר" },
      { word: "כפר", withNikud: "כְּפָר" },
      { word: "שכונה", withNikud: "שְׁכוּנָה" },
      { word: "דירה", withNikud: "דִּירָה" },
    ],
    oddIndex: 3,
    explanation: "דירה היא יחידת מגורים, השאר יישובים/אזורים",
    explanationEn: "Apartment is a living unit, the rest are settlements/areas",
    category: "מקומות",
  },
  {
    id: 8,
    words: [
      { word: "סבא", withNikud: "סָבָא" },
      { word: "סבתא", withNikud: "סָבְתָא" },
      { word: "דוד", withNikud: "דּוֹד" },
      { word: "חבר", withNikud: "חָבֵר" },
    ],
    oddIndex: 3,
    explanation: "חבר אינו בן משפחה, השאר קרובי משפחה",
    explanationEn: "Friend is not family, the rest are relatives",
    category: "משפחה",
  },
  {
    id: 9,
    words: [
      { word: "כותב", withNikud: "כּוֹתֵב" },
      { word: "קורא", withNikud: "קוֹרֵא" },
      { word: "לומד", withNikud: "לוֹמֵד" },
      { word: "כתיבה", withNikud: "כְּתִיבָה" },
    ],
    oddIndex: 3,
    explanation: "כתיבה היא שם עצם, השאר פעלים בהווה",
    explanationEn: "Writing is a noun, the rest are present tense verbs",
    category: "דקדוק",
  },
  {
    id: 10,
    words: [
      { word: "מהר", withNikud: "מַהֵר" },
      { word: "לאט", withNikud: "לְאַט" },
      { word: "טוב", withNikud: "טוֹב" },
      { word: "מהיר", withNikud: "מָהִיר" },
    ],
    oddIndex: 3,
    explanation: "מהיר הוא תואר השם, השאר תארי פועל",
    explanationEn: "Fast (adj) is an adjective, the rest are adverbs",
    category: "דקדוק",
  },
  {
    id: 11,
    words: [
      { word: "רגל", withNikud: "רֶגֶל" },
      { word: "יד", withNikud: "יָד" },
      { word: "אוזן", withNikud: "אֹזֶן" },
      { word: "לב", withNikud: "לֵב" },
    ],
    oddIndex: 3,
    explanation: "לב הוא איבר פנימי, השאר איברים חיצוניים",
    explanationEn: "Heart is internal, the rest are external body parts",
    category: "גוף",
  },
  {
    id: 12,
    words: [
      { word: "בוקר", withNikud: "בֹּקֶר" },
      { word: "צהריים", withNikud: "צָהֳרַיִם" },
      { word: "ערב", withNikud: "עֶרֶב" },
      { word: "שעה", withNikud: "שָׁעָה" },
    ],
    oddIndex: 3,
    explanation: "שעה היא יחידת זמן, השאר חלקי היום",
    explanationEn: "Hour is a time unit, the rest are parts of the day",
    category: "זמן",
  },
  {
    id: 13,
    words: [
      { word: "עשיר", withNikud: "עָשִׁיר" },
      { word: "עני", withNikud: "עָנִי" },
      { word: "זול", withNikud: "זוֹל" },
      { word: "עושר", withNikud: "עֹשֶׁר" },
    ],
    oddIndex: 3,
    explanation: "עושר הוא שם עצם, השאר תארים",
    explanationEn: "Wealth is a noun, the rest are adjectives",
    category: "דקדוק",
  },
  {
    id: 14,
    words: [
      { word: "שמלה", withNikud: "שִׂמְלָה" },
      { word: "חולצה", withNikud: "חֻלְצָה" },
      { word: "מכנסיים", withNikud: "מִכְנָסַיִם" },
      { word: "נעליים", withNikud: "נַעֲלַיִם" },
    ],
    oddIndex: 3,
    explanation: "נעליים הן לרגליים, השאר בגדים לגוף",
    explanationEn: "Shoes are for feet, the rest are body clothes",
    category: "ביגוד",
  },
  {
    id: 15,
    words: [
      { word: "אני", withNikud: "אֲנִי" },
      { word: "אתה", withNikud: "אַתָּה" },
      { word: "הוא", withNikud: "הוּא" },
      { word: "שלי", withNikud: "שֶׁלִּי" },
    ],
    oddIndex: 3,
    explanation: "שלי הוא כינוי קניין, השאר כינויי גוף",
    explanationEn: "Mine is possessive, the rest are personal pronouns",
    category: "דקדוק",
  },
  {
    id: 16,
    words: [
      { word: "על", withNikud: "עַל" },
      { word: "מתחת", withNikud: "מִתַּחַת" },
      { word: "ליד", withNikud: "לְיַד" },
      { word: "גדול", withNikud: "גָּדוֹל" },
    ],
    oddIndex: 3,
    explanation: "גדול הוא תואר, השאר מילות יחס",
    explanationEn: "Big is an adjective, the rest are prepositions",
    category: "דקדוק",
  },
  {
    id: 17,
    words: [
      { word: "לפעמים", withNikud: "לִפְעָמִים" },
      { word: "תמיד", withNikud: "תָּמִיד" },
      { word: "אף פעם", withNikud: "אַף פַּעַם" },
      { word: "פעם", withNikud: "פַּעַם" },
    ],
    oddIndex: 3,
    explanation: "פעם הוא שם עצם (זמן בודד), השאר תארי תדירות",
    explanationEn: "Time/once is a noun, the rest are frequency adverbs",
    category: "דקדוק",
  },
  {
    id: 18,
    words: [
      { word: "שמח", withNikud: "שָׂמֵחַ" },
      { word: "עצוב", withNikud: "עָצוּב" },
      { word: "כועס", withNikud: "כּוֹעֵס" },
      { word: "שמחה", withNikud: "שִׂמְחָה" },
    ],
    oddIndex: 3,
    explanation: "שמחה היא שם עצם, השאר תארים של רגשות",
    explanationEn: "Joy is a noun, the rest are emotion adjectives",
    category: "דקדוק",
  },
  {
    id: 19,
    words: [
      { word: "מורה", withNikud: "מוֹרֶה" },
      { word: "רופא", withNikud: "רוֹפֵא" },
      { word: "נהג", withNikud: "נַהָג" },
      { word: "לימוד", withNikud: "לִימּוּד" },
    ],
    oddIndex: 3,
    explanation: "לימוד הוא פעולה, השאר מקצועות",
    explanationEn: "Learning is an action, the rest are professions",
    category: "מקצועות",
  },
  {
    id: 20,
    words: [
      { word: "ספר", withNikud: "סֵפֶר" },
      { word: "עיתון", withNikud: "עִיתּוֹן" },
      { word: "מכתב", withNikud: "מִכְתָּב" },
      { word: "לקרוא", withNikud: "לִקְרֹא" },
    ],
    oddIndex: 3,
    explanation: "לקרוא הוא פועל, השאר דברים לקריאה",
    explanationEn: "To read is a verb, the rest are things to read",
    category: "דקדוק",
  },
];

