export interface OddOneOutQuestion {
  id: number;
  words: { word: string; withNikud: string }[];
  oddIndex: number;
  explanation: string;
  explanationEn: string;
  category: string;
}

export const easyQuestions: OddOneOutQuestion[] = [
  {
    id: 1,
    words: [
      { word: "תפוח", withNikud: "תַּפּוּחַ" },
      { word: "בננה", withNikud: "בָּנָנָה" },
      { word: "תפוז", withNikud: "תַּפּוּז" },
      { word: "כיסא", withNikud: "כִּיסֵא" },
    ],
    oddIndex: 3,
    explanation: "כיסא הוא רהיט, השאר פירות",
    explanationEn: "Chair is furniture, the rest are fruits",
    category: "פירות",
  },
  {
    id: 2,
    words: [
      { word: "כלב", withNikud: "כֶּלֶב" },
      { word: "חתול", withNikud: "חָתוּל" },
      { word: "ספר", withNikud: "סֵפֶר" },
      { word: "ציפור", withNikud: "צִפּוֹר" },
    ],
    oddIndex: 2,
    explanation: "ספר הוא חפץ, השאר חיות",
    explanationEn: "Book is an object, the rest are animals",
    category: "חיות",
  },
  {
    id: 3,
    words: [
      { word: "אדום", withNikud: "אָדֹם" },
      { word: "ירוק", withNikud: "יָרֹק" },
      { word: "כחול", withNikud: "כָּחֹל" },
      { word: "גדול", withNikud: "גָּדוֹל" },
    ],
    oddIndex: 3,
    explanation: "גדול הוא גודל, השאר צבעים",
    explanationEn: "Big is a size, the rest are colors",
    category: "צבעים",
  },
  {
    id: 4,
    words: [
      { word: "ראשון", withNikud: "רִאשׁוֹן" },
      { word: "שני", withNikud: "שֵׁנִי" },
      { word: "שלישי", withNikud: "שְׁלִישִׁי" },
      { word: "שולחן", withNikud: "שֻׁלְחָן" },
    ],
    oddIndex: 3,
    explanation: "שולחן הוא רהיט, השאר ימים בשבוע",
    explanationEn: "Table is furniture, the rest are days of the week",
    category: "ימים",
  },
  {
    id: 5,
    words: [
      { word: "אמא", withNikud: "אִמָּא" },
      { word: "אבא", withNikud: "אַבָּא" },
      { word: "אח", withNikud: "אָח" },
      { word: "מכונית", withNikud: "מְכוֹנִית" },
    ],
    oddIndex: 3,
    explanation: "מכונית היא כלי רכב, השאר בני משפחה",
    explanationEn: "Car is a vehicle, the rest are family members",
    category: "משפחה",
  },
  {
    id: 6,
    words: [
      { word: "אחד", withNikud: "אֶחָד" },
      { word: "שתיים", withNikud: "שְׁתַּיִם" },
      { word: "שלוש", withNikud: "שָׁלוֹשׁ" },
      { word: "בית", withNikud: "בַּיִת" },
    ],
    oddIndex: 3,
    explanation: "בית הוא מבנה, השאר מספרים",
    explanationEn: "House is a building, the rest are numbers",
    category: "מספרים",
  },
  {
    id: 7,
    words: [
      { word: "לחם", withNikud: "לֶחֶם" },
      { word: "חלב", withNikud: "חָלָב" },
      { word: "גבינה", withNikud: "גְּבִינָה" },
      { word: "עיפרון", withNikud: "עִפָּרוֹן" },
    ],
    oddIndex: 3,
    explanation: "עיפרון הוא כלי כתיבה, השאר מאכלים",
    explanationEn: "Pencil is a writing tool, the rest are foods",
    category: "אוכל",
  },
  {
    id: 8,
    words: [
      { word: "יד", withNikud: "יָד" },
      { word: "רגל", withNikud: "רֶגֶל" },
      { word: "ראש", withNikud: "רֹאשׁ" },
      { word: "דלת", withNikud: "דֶּלֶת" },
    ],
    oddIndex: 3,
    explanation: "דלת היא חפץ, השאר איברי גוף",
    explanationEn: "Door is an object, the rest are body parts",
    category: "גוף",
  },
  {
    id: 9,
    words: [
      { word: "שמש", withNikud: "שֶׁמֶשׁ" },
      { word: "ירח", withNikud: "יָרֵחַ" },
      { word: "כוכב", withNikud: "כּוֹכָב" },
      { word: "מיטה", withNikud: "מִיטָה" },
    ],
    oddIndex: 3,
    explanation: "מיטה היא רהיט, השאר גרמי שמיים",
    explanationEn: "Bed is furniture, the rest are celestial bodies",
    category: "שמיים",
  },
  {
    id: 10,
    words: [
      { word: "מים", withNikud: "מַיִם" },
      { word: "מיץ", withNikud: "מִיץ" },
      { word: "קפה", withNikud: "קָפֶה" },
      { word: "נעל", withNikud: "נַעַל" },
    ],
    oddIndex: 3,
    explanation: "נעל היא ביגוד, השאר משקאות",
    explanationEn: "Shoe is clothing, the rest are drinks",
    category: "שתייה",
  },
];

export const mediumQuestions: OddOneOutQuestion[] = [
  {
    id: 1,
    words: [
      { word: "רופא", withNikud: "רוֹפֵא" },
      { word: "מורה", withNikud: "מוֹרֶה" },
      { word: "שופט", withNikud: "שׁוֹפֵט" },
      { word: "מהיר", withNikud: "מָהִיר" },
    ],
    oddIndex: 3,
    explanation: "מהיר היא תואר, השאר מקצועות",
    explanationEn: "Fast is an adjective, the rest are professions",
    category: "מקצועות",
  },
  {
    id: 2,
    words: [
      { word: "הלך", withNikud: "הָלַךְ" },
      { word: "רץ", withNikud: "רָץ" },
      { word: "קפץ", withNikud: "קָפַץ" },
      { word: "יפה", withNikud: "יָפֶה" },
    ],
    oddIndex: 3,
    explanation: "יפה היא תואר, השאר פעלים של תנועה",
    explanationEn: "Beautiful is an adjective, the rest are movement verbs",
    category: "פעלים",
  },
  {
    id: 3,
    words: [
      { word: "תל אביב", withNikud: "תֵּל אָבִיב" },
      { word: "ירושלים", withNikud: "יְרוּשָׁלַיִם" },
      { word: "חיפה", withNikud: "חֵיפָה" },
      { word: "ישראל", withNikud: "יִשְׂרָאֵל" },
    ],
    oddIndex: 3,
    explanation: "ישראל היא מדינה, השאר ערים",
    explanationEn: "Israel is a country, the rest are cities",
    category: "גאוגרפיה",
  },
  {
    id: 4,
    words: [
      { word: "שמח", withNikud: "שָׂמֵחַ" },
      { word: "עצוב", withNikud: "עָצוּב" },
      { word: "כועס", withNikud: "כּוֹעֵס" },
      { word: "לרוץ", withNikud: "לָרוּץ" },
    ],
    oddIndex: 3,
    explanation: "לרוץ הוא פועל, השאר רגשות",
    explanationEn: "To run is a verb, the rest are emotions",
    category: "רגשות",
  },
  {
    id: 5,
    words: [
      { word: "ינואר", withNikud: "יָנוּאָר" },
      { word: "פברואר", withNikud: "פֶבְּרוּאָר" },
      { word: "מרץ", withNikud: "מֶרְץ" },
      { word: "שבת", withNikud: "שַׁבָּת" },
    ],
    oddIndex: 3,
    explanation: "שבת הוא יום בשבוע, השאר חודשים",
    explanationEn: "Saturday is a day, the rest are months",
    category: "זמן",
  },
  {
    id: 6,
    words: [
      { word: "כתב", withNikud: "כָּתַב" },
      { word: "קרא", withNikud: "קָרָא" },
      { word: "למד", withNikud: "לָמַד" },
      { word: "קטן", withNikud: "קָטָן" },
    ],
    oddIndex: 3,
    explanation: "קטן הוא תואר, השאר פעלים",
    explanationEn: "Small is an adjective, the rest are verbs",
    category: "פעלים",
  },
  {
    id: 7,
    words: [
      { word: "מטבח", withNikud: "מִטְבָּח" },
      { word: "סלון", withNikud: "סָלוֹן" },
      { word: "חדר שינה", withNikud: "חֲדַר שֵׁינָה" },
      { word: "רחוב", withNikud: "רְחוֹב" },
    ],
    oddIndex: 3,
    explanation: "רחוב הוא מקום חיצוני, השאר חדרים בבית",
    explanationEn: "Street is outside, the rest are rooms in a house",
    category: "בית",
  },
  {
    id: 8,
    words: [
      { word: "גיטרה", withNikud: "גִּיטָרָה" },
      { word: "פסנתר", withNikud: "פְּסַנְתֵּר" },
      { word: "כינור", withNikud: "כִּינּוֹר" },
      { word: "ציור", withNikud: "צִיּוּר" },
    ],
    oddIndex: 3,
    explanation: "ציור הוא אמנות חזותית, השאר כלי נגינה",
    explanationEn: "Painting is visual art, the rest are musical instruments",
    category: "מוזיקה",
  },
  {
    id: 9,
    words: [
      { word: "עורך דין", withNikud: "עוֹרֵךְ דִּין" },
      { word: "שוטר", withNikud: "שׁוֹטֵר" },
      { word: "שופט", withNikud: "שׁוֹפֵט" },
      { word: "טבח", withNikud: "טַבָּח" },
    ],
    oddIndex: 3,
    explanation: "טבח עובד במטבח, השאר קשורים למשפט",
    explanationEn: "Chef works in kitchen, the rest are related to law",
    category: "מקצועות",
  },
  {
    id: 10,
    words: [
      { word: "אתמול", withNikud: "אֶתְמוֹל" },
      { word: "היום", withNikud: "הַיּוֹם" },
      { word: "מחר", withNikud: "מָחָר" },
      { word: "פה", withNikud: "פֹּה" },
    ],
    oddIndex: 3,
    explanation: "פה הוא מקום, השאר זמנים",
    explanationEn: "Here is a place, the rest are times",
    category: "זמן",
  },
  {
    id: 11,
    words: [
      { word: "כביש", withNikud: "כְּבִישׁ" },
      { word: "מדרכה", withNikud: "מִדְרָכָה" },
      { word: "גשר", withNikud: "גֶּשֶׁר" },
      { word: "מחברת", withNikud: "מַחְבֶּרֶת" },
    ],
    oddIndex: 3,
    explanation: "מחברת היא כלי כתיבה, השאר קשורים לדרכים",
    explanationEn: "Notebook is for writing, the rest are related to roads",
    category: "תחבורה",
  },
  {
    id: 12,
    words: [
      { word: "חורף", withNikud: "חֹרֶף" },
      { word: "קיץ", withNikud: "קַיִץ" },
      { word: "אביב", withNikud: "אָבִיב" },
      { word: "בוקר", withNikud: "בֹּקֶר" },
    ],
    oddIndex: 3,
    explanation: "בוקר הוא זמן ביום, השאר עונות",
    explanationEn: "Morning is time of day, the rest are seasons",
    category: "עונות",
  },
];

export const hardQuestions: OddOneOutQuestion[] = [
  {
    id: 1,
    words: [
      { word: "דמוקרטיה", withNikud: "דֵּמוֹקְרַטְיָה" },
      { word: "מונרכיה", withNikud: "מוֹנַרְכְיָה" },
      { word: "אוליגרכיה", withNikud: "אוֹלִיגַרְכְיָה" },
      { word: "פילוסופיה", withNikud: "פִילוֹסוֹפְיָה" },
    ],
    oddIndex: 3,
    explanation: "פילוסופיה היא תחום מחשבה, השאר שיטות ממשל",
    explanationEn: "Philosophy is a field of thought, the rest are forms of government",
    category: "פוליטיקה",
  },
  {
    id: 2,
    words: [
      { word: "מטאפורה", withNikud: "מֶטָאפוֹרָה" },
      { word: "דימוי", withNikud: "דִּימּוּי" },
      { word: "השאלה", withNikud: "הַשְׁאָלָה" },
      { word: "פסקה", withNikud: "פִּסְקָה" },
    ],
    oddIndex: 3,
    explanation: "פסקה היא מבנה טקסט, השאר אמצעים ספרותיים",
    explanationEn: "Paragraph is text structure, the rest are literary devices",
    category: "ספרות",
  },
  {
    id: 3,
    words: [
      { word: "אוניברסיטה", withNikud: "אוּנִיבֶרְסִיטָה" },
      { word: "מכללה", withNikud: "מִכְלָלָה" },
      { word: "תיכון", withNikud: "תִּיכוֹן" },
      { word: "ספרייה", withNikud: "סִפְרִיָּה" },
    ],
    oddIndex: 3,
    explanation: "ספרייה היא מקום, השאר מוסדות חינוך",
    explanationEn: "Library is a place, the rest are educational institutions",
    category: "חינוך",
  },
  {
    id: 4,
    words: [
      { word: "התלהבות", withNikud: "הִתְלַהֲבוּת" },
      { word: "נלהב", withNikud: "נִלְהָב" },
      { word: "להתלהב", withNikud: "לְהִתְלַהֵב" },
      { word: "התלהב", withNikud: "הִתְלַהֵב" },
    ],
    oddIndex: 0,
    explanation: "התלהבות היא שם עצם, השאר צורות של הפועל",
    explanationEn: "Enthusiasm is a noun, the rest are verb forms",
    category: "דקדוק",
  },
  {
    id: 5,
    words: [
      { word: "על", withNikud: "עַל" },
      { word: "אל", withNikud: "אֶל" },
      { word: "מתחת", withNikud: "מִתַּחַת" },
      { word: "במהירות", withNikud: "בִּמְהִירוּת" },
    ],
    oddIndex: 3,
    explanation: "במהירות היא תואר הפועל, השאר מילות יחס",
    explanationEn: "Quickly is an adverb, the rest are prepositions",
    category: "דקדוק",
  },
  {
    id: 6,
    words: [
      { word: "אקלים", withNikud: "אַקְלִים" },
      { word: "מזג אוויר", withNikud: "מֶזֶג אֲוִיר" },
      { word: "טמפרטורה", withNikud: "טֶמְפֶּרָטוּרָה" },
      { word: "גאוגרפיה", withNikud: "גֵּאוֹגְרַפְיָה" },
    ],
    oddIndex: 3,
    explanation: "גאוגרפיה היא תחום לימוד, השאר קשורים למזג אוויר",
    explanationEn: "Geography is a field of study, the rest are weather-related",
    category: "מדע",
  },
  {
    id: 7,
    words: [
      { word: "משפט", withNikud: "מִשְׁפָּט" },
      { word: "פסקה", withNikud: "פִּסְקָה" },
      { word: "פרק", withNikud: "פֶּרֶק" },
      { word: "סיפור", withNikud: "סִיפּוּר" },
    ],
    oddIndex: 3,
    explanation: "סיפור הוא ז'אנר, השאר חלקי טקסט",
    explanationEn: "Story is a genre, the rest are parts of text",
    category: "כתיבה",
  },
  {
    id: 8,
    words: [
      { word: "אנליזה", withNikud: "אֲנָלִיזָה" },
      { word: "סינתזה", withNikud: "סִינְתֵּזָה" },
      { word: "הערכה", withNikud: "הַעֲרָכָה" },
      { word: "טלוויזיה", withNikud: "טֶלֶוִיזְיָה" },
    ],
    oddIndex: 3,
    explanation: "טלוויזיה היא מכשיר, השאר מיומנויות חשיבה",
    explanationEn: "Television is a device, the rest are thinking skills",
    category: "חשיבה",
  },
  {
    id: 9,
    words: [
      { word: "השערה", withNikud: "הַשְׁעָרָה" },
      { word: "ניסוי", withNikud: "נִיסּוּי" },
      { word: "תצפית", withNikud: "תַּצְפִּית" },
      { word: "דעה", withNikud: "דֵּעָה" },
    ],
    oddIndex: 3,
    explanation: "דעה היא סובייקטיבית, השאר חלקים משיטה מדעית",
    explanationEn: "Opinion is subjective, the rest are parts of scientific method",
    category: "מדע",
  },
  {
    id: 10,
    words: [
      { word: "קפיטליזם", withNikud: "קָפִּיטָלִיזְם" },
      { word: "סוציאליזם", withNikud: "סוֹצְיָאלִיזְם" },
      { word: "קומוניזם", withNikud: "קוֹמוּנִיזְם" },
      { word: "אופטימיזם", withNikud: "אוֹפְּטִימִיזְם" },
    ],
    oddIndex: 3,
    explanation: "אופטימיזם היא גישה נפשית, השאר שיטות כלכליות",
    explanationEn: "Optimism is a mindset, the rest are economic systems",
    category: "כלכלה",
  },
  {
    id: 11,
    words: [
      { word: "ביוגרפיה", withNikud: "בִּיּוֹגְרָפְיָה" },
      { word: "אוטוביוגרפיה", withNikud: "אוֹטוֹבִּיּוֹגְרָפְיָה" },
      { word: "זכרונות", withNikud: "זִכְרוֹנוֹת" },
      { word: "רומן", withNikud: "רוֹמָן" },
    ],
    oddIndex: 3,
    explanation: "רומן הוא בדיוני, השאר ז'אנרים אישיים/עובדתיים",
    explanationEn: "Novel is fiction, the rest are personal/factual genres",
    category: "ספרות",
  },
  {
    id: 12,
    words: [
      { word: "אירוניה", withNikud: "אִירוֹנְיָה" },
      { word: "סרקזם", withNikud: "סַרְקָזְם" },
      { word: "סאטירה", withNikud: "סָטִירָה" },
      { word: "טרגדיה", withNikud: "טְרָגֶדְיָה" },
    ],
    oddIndex: 3,
    explanation: "טרגדיה היא ז'אנר דרמתי, השאר קשורים להומור/לעג",
    explanationEn: "Tragedy is dramatic genre, the rest relate to humor/mockery",
    category: "ספרות",
  },
  {
    id: 13,
    words: [
      { word: "כלכלה", withNikud: "כַּלְכָּלָה" },
      { word: "סוציולוגיה", withNikud: "סוֹצְיוֹלוֹגְיָה" },
      { word: "פסיכולוגיה", withNikud: "פְּסִיכוֹלוֹגְיָה" },
      { word: "ביולוגיה", withNikud: "בִּיּוֹלוֹגְיָה" },
    ],
    oddIndex: 3,
    explanation: "ביולוגיה היא מדע טבע, השאר מדעי החברה",
    explanationEn: "Biology is natural science, the rest are social sciences",
    category: "מדע",
  },
  {
    id: 14,
    words: [
      { word: "אימפריאליזם", withNikud: "אִימְפֶּרְיָאלִיזְם" },
      { word: "קולוניאליזם", withNikud: "קוֹלוֹנְיָאלִיזְם" },
      { word: "נאציונליזם", withNikud: "נָאצְיוֹנָלִיזְם" },
      { word: "רציונליזם", withNikud: "רָצְיוֹנָלִיזְם" },
    ],
    oddIndex: 3,
    explanation: "רציונליזם היא גישה פילוסופית, השאר אידיאולוגיות פוליטיות",
    explanationEn: "Rationalism is philosophical, the rest are political ideologies",
    category: "פוליטיקה",
  },
  {
    id: 15,
    words: [
      { word: "סימפוניה", withNikud: "סִימְפוֹנְיָה" },
      { word: "קונצ'רטו", withNikud: "קוֹנְצֶ'רְטוֹ" },
      { word: "סונטה", withNikud: "סוֹנָטָה" },
      { word: "גלריה", withNikud: "גָּלֶרְיָה" },
    ],
    oddIndex: 3,
    explanation: "גלריה היא מקום, השאר צורות מוזיקליות",
    explanationEn: "Gallery is a place, the rest are musical forms",
    category: "מוזיקה",
  },
];
