export type PastTenseQuestion = {
  number: number;
  sentence: string;
  options: string[];
  answer: string;
  translation: string;
};

export const pastTenseQuestions: PastTenseQuestion[] = [
  {
    number: 1,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 2,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 3,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 4,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 5,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 6,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 7,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 8,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 9,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 10,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 11,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 12,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 13,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 14,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 15,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 16,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 17,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 18,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 19,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 20,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 21,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 22,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 23,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 24,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 25,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 26,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 27,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 28,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 29,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 30,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 31,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 32,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 33,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 34,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 35,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 36,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 37,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 38,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 39,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 40,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
    {
    number: 41,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 42,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 43,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 44,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 45,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 46,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 47,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 48,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 49,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 50,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 51,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 52,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 53,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 54,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 55,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 56,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 57,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 58,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 59,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 60,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 61,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 62,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 63,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 64,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 65,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 66,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 67,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 68,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 69,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 70,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 71,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 72,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 73,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 74,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 75,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 76,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 77,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 78,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 79,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 80,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 81,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 82,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 83,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 84,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 85,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 86,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 87,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 88,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 89,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 90,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
  {
    number: 91,
    sentence: "אני ___ פיצה בערב.",
    options: ["אכלתי", "אוכל", "יאכל"],
    answer: "אכלתי",
    translation: "I ___ pizza in the evening. (ate)",
  },
  {
    number: 92,
    sentence: "אתה ___ מים אחרי הריצה.",
    options: ["שתית", "שותה", "תשתה"],
    answer: "שתית",
    translation: "You ___ water after the run. (drank)",
  },
  {
    number: 93,
    sentence: "היא ___ לבית הספר ברגל.",
    options: ["הלכה", "הולכת", "תלך"],
    answer: "הלכה",
    translation: "She ___ to school by foot. (walked)",
  },
  {
    number: 94,
    sentence: "אנחנו ___ לסרט חדש בקולנוע.",
    options: ["באנו", "באים", "נבוא"],
    answer: "באנו",
    translation: "We ___ to a new movie at the cinema. (came)",
  },
  {
    number: 95,
    sentence: "הם ___ סרט מעניין בטלוויזיה.",
    options: ["ראו", "רואים", "יראו"],
    answer: "ראו",
    translation: "They ___ an interesting movie on TV. (watched/saw)",
  },
  {
    number: 96,
    sentence: "אתן ___ את ההרצאה בקשב רב.",
    options: ["שמעתן", "שומעות", "תשמעו"],
    answer: "שמעתן",
    translation: "You (f. pl.) ___ the lecture attentively. (listened)",
  },
  {
    number: 97,
    sentence: "הוא ___ עם המורה על הפרויקט.",
    options: ["דיבר", "מדבר", "ידבר"],
    answer: "דיבר",
    translation: "He ___ with the teacher about the project. (spoke)",
  },
  {
    number: 98,
    sentence: "אני ___ להם את האמת.",
    options: ["אמרתי", "אומר", "אומרת"],
    answer: "אמרתי",
    translation: "I ___ them the truth. (told)",
  },
  {
    number: 99,
    sentence: "היא ___ מוקדם כי הייתה עייפה.",
    options: ["ישנה", "ישנה", "תישן"],
    answer: "ישנה",
    translation: "She ___ early because she was tired. (slept)",
  },
  {
    number: 100,
    sentence: "הם ___ בשעה חמש כדי להספיק לרכבת.",
    options: ["קמו", "קמים", "יקומו"],
    answer: "קמו",
    translation: "They ___ at five to catch the train. (got up)",
  },
];
