
export const readingText = `רון גר בעיר קטנה ליד הים. בכל סוף שבוע הוא נפגש עם חברים בחוף המקומי. הם מביאים מחצלת, כדור, שתייה קרה וחטיפים. אחרי המשחקים והרחצה במים, הם הולכים למסעדה קרובה לאכול יחד. רון אוהב להזמין חומוס, סלט ירקות טרי ופיתה חמה. לפעמים הם גם קונים גלידה בטעמים מיוחדים כמו פסיפלורה, קוקוס או וניל עם בוטנים.`;

export const translationMap: { [hebrewWord: string]: string } = {
  "רון": "Ron",
  "עיר": "city",
  "קטנה": "small",
  "ליד": "near",
  "הים": "the sea",
  "סוף שבוע": "weekend",
  "נפגש": "meets",
  "חברים": "friends",
  "חוף": "beach",
  "המקומי": "the local",
  "מביאים": "bring",
  "מחצלת": "mat",
  "כדור": "ball",
  "שתייה": "drinks",
  "קרה": "cold",
  "חטיפים": "snacks",
  "משחקים": "games / playing",
  "רחצה": "swimming",
  "במים": "in the water",
  "הולכים": "go",
  "מסעדה": "restaurant",
  "קרובה": "nearby",
  "לאכול": "to eat",
  "יחד": "together",
  "אוהב": "likes",
  "להזמין": "to order",
  "חומוס": "hummus",
  "סלט": "salad",
  "ירקות": "vegetables",
  "טרי": "fresh",
  "פיתה": "pita",
  "חמה": "warm",
  "לפעמים": "sometimes",
  "גם": "also",
  "קונים": "buy",
  "גלידה": "ice cream",
  "בטעמים": "with flavors",
  "מיוחדים": "special",
  "פסיפלורה": "passionfruit",
  "קוקוס": "coconut",
  "וניל": "vanilla",
  "בוטנים": "peanuts",
  "או": "or"
};
