export interface QuestionWordQuestion {
  id: number;
  sentence: string;
  sentenceWithNikud: string;
  options: string[];
  answer: string;
  translation: string;
}

export const questionWordsVocabulary = [
  { word: "מה", withNikud: "מָה", meaning: "What" },
  { word: "מי", withNikud: "מִי", meaning: "Who" },
  { word: "איפה", withNikud: "אֵיפֹה", meaning: "Where" },
  { word: "מתי", withNikud: "מָתַי", meaning: "When" },
  { word: "למה", withNikud: "לָמָה", meaning: "Why" },
  { word: "איך", withNikud: "אֵיךְ", meaning: "How" },
  { word: "כמה", withNikud: "כַּמָּה", meaning: "How much / How many" },
  { word: "איזה", withNikud: "אֵיזֶה", meaning: "Which (m)" },
  { word: "איזו", withNikud: "אֵיזוֹ", meaning: "Which (f)" },
  { word: "האם", withNikud: "הַאִם", meaning: "Is it? / Do?" },
];

export const easyQuestions: QuestionWordQuestion[] = [
  {
    id: 1,
    sentence: "___ השם שלך?",
    sentenceWithNikud: "___ הַשֵּׁם שֶׁלְּךָ?",
    options: ["מה", "מי", "איפה"],
    answer: "מה",
    translation: "What is your name?",
  },
  {
    id: 2,
    sentence: "___ אתה גר?",
    sentenceWithNikud: "___ אַתָּה גָּר?",
    options: ["איפה", "מתי", "למה"],
    answer: "איפה",
    translation: "Where do you live?",
  },
  {
    id: 3,
    sentence: "___ זה?",
    sentenceWithNikud: "___ זֶה?",
    options: ["מי", "מה", "איך"],
    answer: "מי",
    translation: "Who is this?",
  },
  {
    id: 4,
    sentence: "___ אתה בא?",
    sentenceWithNikud: "___ אַתָּה בָּא?",
    options: ["מתי", "איפה", "מה"],
    answer: "מתי",
    translation: "When are you coming?",
  },
  {
    id: 5,
    sentence: "___ אתה עייף?",
    sentenceWithNikud: "___ אַתָּה עָיֵף?",
    options: ["למה", "איך", "מי"],
    answer: "למה",
    translation: "Why are you tired?",
  },
  {
    id: 6,
    sentence: "___ אומרים 'תודה' באנגלית?",
    sentenceWithNikud: "___ אוֹמְרִים 'תּוֹדָה' בְּאַנְגְּלִית?",
    options: ["איך", "מה", "מתי"],
    answer: "איך",
    translation: "How do you say 'thank you' in English?",
  },
  {
    id: 7,
    sentence: "___ זה עולה?",
    sentenceWithNikud: "___ זֶה עוֹלֶה?",
    options: ["כמה", "מה", "איפה"],
    answer: "כמה",
    translation: "How much does it cost?",
  },
  {
    id: 8,
    sentence: "___ ספר אתה קורא?",
    sentenceWithNikud: "___ סֵפֶר אַתָּה קוֹרֵא?",
    options: ["איזה", "מי", "למה"],
    answer: "איזה",
    translation: "Which book are you reading?",
  },
  {
    id: 9,
    sentence: "___ את רוצה קפה?",
    sentenceWithNikud: "___ אַתְּ רוֹצָה קָפֶה?",
    options: ["האם", "מה", "איך"],
    answer: "האם",
    translation: "Do you want coffee?",
  },
  {
    id: 10,
    sentence: "___ הבית שלך?",
    sentenceWithNikud: "___ הַבַּיִת שֶׁלְּךָ?",
    options: ["איפה", "מתי", "למה"],
    answer: "איפה",
    translation: "Where is your house?",
  },
];

export const mediumQuestions: QuestionWordQuestion[] = [
  {
    id: 1,
    sentence: "___ אתה לומד עברית?",
    sentenceWithNikud: "___ אַתָּה לוֹמֵד עִבְרִית?",
    options: ["למה", "איפה", "מי"],
    answer: "למה",
    translation: "Why are you learning Hebrew?",
  },
  {
    id: 2,
    sentence: "___ הגעת לישראל?",
    sentenceWithNikud: "___ הִגַּעְתָּ לְיִשְׂרָאֵל?",
    options: ["מתי", "מה", "איך"],
    answer: "מתי",
    translation: "When did you arrive in Israel?",
  },
  {
    id: 3,
    sentence: "___ אנשים יש בכיתה?",
    sentenceWithNikud: "___ אֲנָשִׁים יֵשׁ בַּכִּיתָה?",
    options: ["כמה", "איזה", "מי"],
    answer: "כמה",
    translation: "How many people are in the class?",
  },
  {
    id: 4,
    sentence: "___ עיר את גרה?",
    sentenceWithNikud: "___ עִיר אַתְּ גָּרָה?",
    options: ["באיזו", "מה", "למה"],
    answer: "באיזו",
    translation: "In which city do you live?",
  },
  {
    id: 5,
    sentence: "___ המורה שלך?",
    sentenceWithNikud: "___ הַמּוֹרָה שֶׁלְּךָ?",
    options: ["מי", "מה", "איפה"],
    answer: "מי",
    translation: "Who is your teacher?",
  },
  {
    id: 6,
    sentence: "___ אפשר להגיע לתחנה?",
    sentenceWithNikud: "___ אֶפְשָׁר לְהַגִּיעַ לַתַּחֲנָה?",
    options: ["איך", "מתי", "מי"],
    answer: "איך",
    translation: "How can I get to the station?",
  },
  {
    id: 7,
    sentence: "___ אתה עושה בסוף שבוע?",
    sentenceWithNikud: "___ אַתָּה עוֹשֶׂה בְּסוֹף שָׁבוּעַ?",
    options: ["מה", "מי", "האם"],
    answer: "מה",
    translation: "What are you doing on the weekend?",
  },
  {
    id: 8,
    sentence: "___ שעה הפגישה?",
    sentenceWithNikud: "___ שָׁעָה הַפְּגִישָׁה?",
    options: ["באיזו", "למה", "מי"],
    answer: "באיזו",
    translation: "At what time is the meeting?",
  },
  {
    id: 9,
    sentence: "___ אתה מכיר את דני?",
    sentenceWithNikud: "___ אַתָּה מַכִּיר אֶת דָּנִי?",
    options: ["האם", "מה", "איפה"],
    answer: "האם",
    translation: "Do you know Danny?",
  },
  {
    id: 10,
    sentence: "___ לא באת אתמול?",
    sentenceWithNikud: "___ לֹא בָּאתָ אֶתְמוֹל?",
    options: ["למה", "מתי", "איך"],
    answer: "למה",
    translation: "Why didn't you come yesterday?",
  },
  {
    id: 11,
    sentence: "___ קראת לי?",
    sentenceWithNikud: "___ קָרָאתָ לִי?",
    options: ["למה", "מה", "איפה"],
    answer: "למה",
    translation: "Why did you call me?",
  },
  {
    id: 12,
    sentence: "___ יודע את התשובה?",
    sentenceWithNikud: "___ יוֹדֵעַ אֶת הַתְּשׁוּבָה?",
    options: ["מי", "מה", "איך"],
    answer: "מי",
    translation: "Who knows the answer?",
  },
];

export const hardQuestions: QuestionWordQuestion[] = [
  {
    id: 1,
    sentence: "___ הייתה התגובה שלו כשסיפרת לו?",
    sentenceWithNikud: "___ הָיְתָה הַתְּגוּבָה שֶׁלּוֹ כְּשֶׁסִּפַּרְתָּ לוֹ?",
    options: ["מה", "איך", "למה"],
    answer: "מה",
    translation: "What was his reaction when you told him?",
  },
  {
    id: 2,
    sentence: "___ הצלחת לפתור את הבעיה?",
    sentenceWithNikud: "___ הִצְלַחְתָּ לִפְתֹּר אֶת הַבְּעָיָה?",
    options: ["איך", "מה", "מי"],
    answer: "איך",
    translation: "How did you manage to solve the problem?",
  },
  {
    id: 3,
    sentence: "___ זמן לוקח להגיע לשם?",
    sentenceWithNikud: "___ זְמַן לוֹקֵחַ לְהַגִּיעַ לְשָׁם?",
    options: ["כמה", "מתי", "איפה"],
    answer: "כמה",
    translation: "How much time does it take to get there?",
  },
  {
    id: 4,
    sentence: "___ מבין הספרים האלה הכי מעניין?",
    sentenceWithNikud: "___ מִבֵּין הַסְּפָרִים הָאֵלֶּה הֲכִי מְעַנְיֵן?",
    options: ["איזה", "מה", "מי"],
    answer: "איזה",
    translation: "Which of these books is the most interesting?",
  },
  {
    id: 5,
    sentence: "___ כדאי להתחיל בפרויקט הזה?",
    sentenceWithNikud: "___ כְּדַאי לְהַתְחִיל בַּפְּרוֹיֶקְט הַזֶּה?",
    options: ["מתי", "מה", "מי"],
    answer: "מתי",
    translation: "When should we start this project?",
  },
  {
    id: 6,
    sentence: "___ אחראי על הנושא הזה?",
    sentenceWithNikud: "___ אַחְרָאִי עַל הַנּוֹשֵׂא הַזֶּה?",
    options: ["מי", "מה", "איך"],
    answer: "מי",
    translation: "Who is responsible for this matter?",
  },
  {
    id: 7,
    sentence: "___ הממשלה החליטה לשנות את החוק?",
    sentenceWithNikud: "___ הַמֶּמְשָׁלָה הֶחְלִיטָה לְשַׁנּוֹת אֶת הַחֹק?",
    options: ["למה", "מתי", "איפה"],
    answer: "למה",
    translation: "Why did the government decide to change the law?",
  },
  {
    id: 8,
    sentence: "___ אפשר לדעת אם המידע נכון?",
    sentenceWithNikud: "___ אֶפְשָׁר לָדַעַת אִם הַמֵּידָע נָכוֹן?",
    options: ["איך", "מה", "האם"],
    answer: "איך",
    translation: "How can we know if the information is correct?",
  },
  {
    id: 9,
    sentence: "___ התקיימה הפגישה האחרונה?",
    sentenceWithNikud: "___ הִתְקַיְּמָה הַפְּגִישָׁה הָאַחֲרוֹנָה?",
    options: ["איפה", "מתי", "למה"],
    answer: "איפה",
    translation: "Where did the last meeting take place?",
  },
  {
    id: 10,
    sentence: "___ שעות ביום את עובדת?",
    sentenceWithNikud: "___ שָׁעוֹת בַּיּוֹם אַתְּ עוֹבֶדֶת?",
    options: ["כמה", "באיזו", "מתי"],
    answer: "כמה",
    translation: "How many hours a day do you work?",
  },
  {
    id: 11,
    sentence: "___ ההבדל בין שתי האפשרויות?",
    sentenceWithNikud: "___ הַהֶבְדֵּל בֵּין שְׁתֵּי הָאֶפְשָׁרוּיוֹת?",
    options: ["מה", "איך", "מי"],
    answer: "מה",
    translation: "What is the difference between the two options?",
  },
  {
    id: 12,
    sentence: "___ תדע שהגעת למקום הנכון?",
    sentenceWithNikud: "___ תֵּדַע שֶׁהִגַּעְתָּ לַמָּקוֹם הַנָּכוֹן?",
    options: ["איך", "מתי", "מה"],
    answer: "איך",
    translation: "How will you know you've arrived at the right place?",
  },
  {
    id: 13,
    sentence: "___ יש צורך בתהליך כל כך ארוך?",
    sentenceWithNikud: "___ יֵשׁ צֹרֶךְ בְּתַהֲלִיךְ כָּל כָּךְ אָרֹךְ?",
    options: ["למה", "האם", "מה"],
    answer: "למה",
    translation: "Why is such a long process necessary?",
  },
  {
    id: 14,
    sentence: "___ היא החליטה לעזוב את העבודה?",
    sentenceWithNikud: "___ הִיא הֶחְלִיטָה לַעֲזֹב אֶת הָעֲבוֹדָה?",
    options: ["למה", "מה", "איפה"],
    answer: "למה",
    translation: "Why did she decide to leave the job?",
  },
  {
    id: 15,
    sentence: "___ אתה מתכוון בדיוק?",
    sentenceWithNikud: "___ אַתָּה מִתְכַּוֵּן בְּדִיּוּק?",
    options: ["למה", "מה", "איך"],
    answer: "למה",
    translation: "What exactly do you mean?",
  },
];
